import { ClipboardListIcon } from "@heroicons/react/outline";
import React, { useEffect, useState } from "react";

import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Cards from "../components/Cards";
import InfoCard from "../components/InfoCard";
import styles from "../styles/Home.module.css";
import Hotels from "../components/Hotels";
import Filter from "../components/Filter";
import axios from "axios";

export default function Home({ result }) {
  // const [propertyData, setPropertyData] = useState();
  // setPropertyData(result);

  // useEffect(() => {
  //   getPropertyResults();
  // }, []);

  return (
    <div className="">
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Filter />
      <Hotels result={result} />
    </div>
  );
}

export async function getServerSideProps() {
  const options = {
    method: "GET",
    headers: {
      "X-RapidAPI-Key": "f8da552677msh3cc69df4e6e27e2p13da2ajsnaafab4748640",
      "X-RapidAPI-Host": "airbnb13.p.rapidapi.com",
    },
  };

  const api = await fetch(
    "https://airbnb13.p.rapidapi.com/search-location?location=Europe&checkin=2022-12-22&checkout=2022-12-24&adults=1&children=0&infants=0&page=1",
    options
  );
  const response = await api.json();
  console.log("index js res", response);
  const result = response.results;

  return {
    props: {
      result,
    },
  };
}
