import { ClipboardListIcon } from "@heroicons/react/outline";
import React, { useEffect, useState } from "react";

import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Cards from "../components/Cards";
import InfoCard from "../components/InfoCard";
import styles from "../styles/Home.module.css";
import Hotels from "../components/Hotels";
import Filter from "../components/Filter";

export default function Home() {
  const [propertyData, setPropertyData] = useState();

  const getPropertyResults = async () => {
    console.log("get property start");
    // console.log(locationData);
    const locationUrl = `https://hotels4.p.rapidapi.com/properties/list?destinationId=1757510&pageNumber=1&pageSize=25&checkIn=2022-09-11&checkOut=2022-09-14&adults1=1&sortOrder=PRICE&locale=en_US&currency=USD`;

    const options = {
      method: "GET",
      headers: {
        "X-RapidAPI-Key": "f8da552677msh3cc69df4e6e27e2p13da2ajsnaafab4748640",
        "X-RapidAPI-Host": "hotels4.p.rapidapi.com",
      },
    };

    const api = await fetch(locationUrl, options);
    const data = await api.json();
    setPropertyData(data.data.body.searchResults.results);
    console.log("get property done");
  };

  useEffect(() => {
    getPropertyResults();
  }, []);

  return (
    <div className="">
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Filter />
      <Hotels data={propertyData} />
    </div>
  );
}
